In [1]:
import numpy as np

## 1. Creating numpy arrays

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


* Checking datatype

In [3]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

2.1.3


* Create ndarray from tuple

In [7]:
arr2 = np.array((1,2,3,4,5))
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


* Dimensions of array

In [12]:
arr3 = np.array([5,6,7,8])
print(arr3)
print(f"Dimension of the array: {arr3.ndim}")

[5 6 7 8]
Dimension of the array: 1


* 0-D Array

In [4]:
arr0D = np.array(42)
print(arr0D)
print(f"Dimension: {arr0D.ndim}")

42
Dimension: 0


* 1-D Array

In [18]:
arr1D = np.array([1,2,3,4])
print(arr1D)
print(f"Dimension: {arr1D.ndim}")

[1 2 3 4]
Dimension: 1


* 2-D Array

In [31]:
arr2D = np.array([[2,3],[4,5],[6,7]])
print(arr2D)
print(f"Dimension : {arr2D.ndim}")
print(arr2D.shape)

[[2 3]
 [4 5]
 [6 7]]
Dimension : 2
(3, 2)


* 3-D Array

In [32]:
arr3D = np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr3D)
print(f"Dimension: {arr3D.ndim}")
print(f"Shape: {arr3D.shape}")

[[[1 2 3 4]
  [5 6 7 8]]]
Dimension: 3
Shape: (1, 2, 4)


* Higher Dimensional Array

In [24]:
arrHigh = np.array([1,2,3,4],ndmin = 5)
print(arrHigh)
print(f"Dimension: {arrHigh.ndim}")

[[[[[1 2 3 4]]]]]
Dimension: 5


In [27]:
arrHigh.shape

(1, 1, 1, 1, 4)

- We can add as many dimension as we want by using (ndmin = value) when creting the numpy array.

In [26]:
arrAsArray = np.asarray([1,2,3,4])
print(arrAsArray)
print(type(arrAsArray))

[1 2 3 4]
<class 'numpy.ndarray'>


# 2. Array Indexxing

In [5]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(f"The first element of the array: {arr1[0]}")
print(f"The second element of the array: {arr1[1]}")
print(f"The third element of the array: {arr1[2]}")
print(f"The fourth element of the array: {arr1[3]}")
len(arr1)

[1 2 3 4]
The first element of the array: 1
The second element of the array: 2
The third element of the array: 3
The fourth element of the array: 4


4

In [8]:
arr2D = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2D)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
arr2D.shape

(2, 4)

In [11]:
arr2D[1][0] # [row][col]

np.int64(5)

In [12]:
print(arr2D[0][2]+arr2D[1][1])

9


In [18]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [19]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr.shape)

6
(2, 2, 3)


In [22]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1] [-1])

Last element from 2nd dim:  10


# 3. Array slicing

In [26]:
arr = np.array([1,2,3,4])
print(arr[:2])
print(arr[::2])
print(arr[1:])

[1 2]
[1 3]
[2 3 4]


In [27]:
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2[1][2:])

[6 7]


In [28]:
arr2[1,1:3]

array([5, 6])

In [29]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [35]:
# 3. Using arange
arr3 = np.arange(0, 12, 2)  # start=0, stop=10, step=2
print("Arange array:", arr3.reshape(2,3))

Arange array: [[ 0  2  4]
 [ 6  8 10]]


# 4. Checking the Data Type of an Array

In [19]:

arr = np.array([1,2,3,45,6,7])
print(arr)
print(arr.dtype)


[ 1  2  3 45  6  7]
int64


In [20]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [39]:
arr = np.array([1.1,2.1,3.1,4.1])
arr1 = arr.astype('int16')
print(arr1.dtype)

int16


In [44]:
arr = np.array([-1, 0, 3,None,""])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True False False]
bool


# 5. NumPy Array Copy vs View

* Copy 

In [52]:
arr = np.array([1,2,3,42,50,100,102])
arr_c = arr[:]
arr_cc = arr.copy()
arr[0] = 12
print(arr)
print(arr_cc)

[ 12   2   3  42  50 100 102]
[  1  50   3  42  50 100 102]


* View

In [56]:
arr = np.array([10,20,30,40,50,300])
arr_view = arr.view()
arr[-1]  = 60
arr_view[2] = 5000
print(arr)
print(arr_view)

[  10   20 5000   40   50   60]
[  10   20 5000   40   50   60]
