In [1]:
import numpy as np

## 1. Creating numpy arrays

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


* Checking datatype

In [3]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

2.1.3


* Create ndarray from tuple

In [7]:
arr2 = np.array((1,2,3,4,5))
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


* Dimensions of array

In [12]:
arr3 = np.array([5,6,7,8])
print(arr3)
print(f"Dimension of the array: {arr3.ndim}")

[5 6 7 8]
Dimension of the array: 1


* 0-D Array

In [14]:
arr0D = np.array(42)
print(arr0D)
print(f"Dimension: {arr0D.ndim}")

42
Dimension: 0


* 1-D Array

In [18]:
arr1D = np.array([1,2,3,4])
print(arr1D)
print(f"Dimension: {arr1D.ndim}")

[1 2 3 4]
Dimension: 1


* 2-D Array

In [31]:
arr2D = np.array([[2,3],[4,5],[6,7]])
print(arr2D)
print(f"Dimension : {arr2D.ndim}")
print(arr2D.shape)

[[2 3]
 [4 5]
 [6 7]]
Dimension : 2
(3, 2)


* 3-D Array

In [32]:
arr3D = np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr3D)
print(f"Dimension: {arr3D.ndim}")
print(f"Shape: {arr3D.shape}")

[[[1 2 3 4]
  [5 6 7 8]]]
Dimension: 3
Shape: (1, 2, 4)


* Higher Dimensional Array

In [24]:
arrHigh = np.array([1,2,3,4],ndmin = 5)
print(arrHigh)
print(f"Dimension: {arrHigh.ndim}")

[[[[[1 2 3 4]]]]]
Dimension: 5


In [27]:
arrHigh.shape

(1, 1, 1, 1, 4)

- We can add as many dimension as we want by using (ndim = value) when creting the numpy array.

In [26]:
arrAsArray = np.asarray([1,2,3,4])
print(arrAsArray)
print(type(arrAsArray))

[1 2 3 4]
<class 'numpy.ndarray'>
